name: 'Deployment'
description: 'Trigger deployment webhook and report to Sentry'
inputs:
  service:
    description: 'Service name'
    required: true
  component:
    description: 'Component name'
    required: true
    default: 'deployment'
  organization:
    description: 'Organization name'
    required: false
  repository:
    description: 'Repository name'
    required: false
  sentry_dsn:
    description: 'Sentry DSN'
    required: false
  auth:
    description: 'Basic Auth for Webhook'
    required: true
  deploy_image:
    description: 'Docker image'
    required: true
    default: 'git.makecodes.dev/viaartistica/crm-backend'
  deploy_version:
    description: 'Version to deploy'
    required: true
    default: 'qa'
  deploy_webhook_url:
    description: 'Webhook URL'
    required: true
    default: 'https://n8n.ops.makecodes.dev/webhook/viaartistica-crm-qa-deployments'
  deploy_timeout_ms:
    description: 'Timeout in ms'
    required: false
    default: '3600000'
  enable_influxdb:
    description: 'Enable InfluxDB reporting'
    required: false
    default: 'false'
  influxdb_url:
    description: 'InfluxDB URL'
    required: false
  influxdb_token:
    description: 'InfluxDB Token'
    required: false
  influxdb_org:
    description: 'InfluxDB Organization'
    required: false
  influxdb_bucket:
    description: 'InfluxDB Bucket'
    required: false

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: Install dependencies
      shell: bash
      run: |
        export NODE_OPTIONS="--no-deprecation"
        cd ${{ github.action_path }}
        npm install -g pnpm
        pnpm install --prod

    - name: Run deployment script
      shell: bash
      run: node ${{ github.action_path }}/main.js
      env:
        NODE_OPTIONS: "--no-deprecation"
        SERVICE: ${{ inputs.service }}
        COMPONENT: ${{ inputs.component }}
        ORGANIZATION: ${{ inputs.organization || github.repository_owner }}
        REPOSITORY: ${{ inputs.repository || github.event.repository.name }}
        SENTRY_DSN: ${{ inputs.sentry_dsn }}
        AUTH: ${{ inputs.auth }}
        DEPLOY_IMAGE: ${{ inputs.deploy_image }}
        DEPLOY_VERSION: ${{ inputs.deploy_version }}
        DEPLOY_WEBHOOK_URL: ${{ inputs.deploy_webhook_url }}
        DEPLOY_TIMEOUT_MS: ${{ inputs.deploy_timeout_ms }}
        ENABLE_INFLUXDB: ${{ inputs.enable_influxdb }}
        INFLUXDB_URL: ${{ inputs.influxdb_url }}
        INFLUXDB_TOKEN: ${{ inputs.influxdb_token }}
        INFLUXDB_ORG: ${{ inputs.influxdb_org }}
        INFLUXDB_BUCKET: ${{ inputs.influxdb_bucket }}
